User.create(username: "Brian", password: "Stronk", storyteller: true)
User.create(username: "Susan", password: "Stronker", storyteller: true)
User.create(username: "John", password: "Password1")
User.create(username: "Phillis", password: "Password2")
User.create(username: "Mike", password: "Password3")
User.create(username: "PJ", password: "Password4")
User.create(username: "Horace", password: "Password5")
# one = Post.create(conente: "rar rar rar", player_access: true)
# two = Post.create(conente: "blah blah blah", player_access: true)
# three = Post.create(conente: "boopity boo",)
# four = Post.create(conente: "boom shakalaka", player_access: true)
# five = Post.create(conente: "inaudible noises")